### ISSUE TITLE
Support more MVNO

### ISSUE THREAD

**Issue by J0s3f** [flowolf/yessssms#1]
Hi,

it would be great if there would be a config option to support different A1 brands.

I tested the following two of which I have accounts and they work with the settings below:

Educom:

    _LOGIN_URL = "https://educom.kontomanager.at/index.php"
    _LOGOUT_URL = "https://educom.kontomanager.at/index.php?dologout=2"
    _KONTOMANAGER_URL = "https://educom.kontomanager.at/kundendaten.php"
    _WEBSMS_URL = "https://educom.kontomanager.at/websms_send.php"

SIMfonie:

    _LOGIN_URL = "https://simfonie.kontomanager.at/index.php"
    _LOGOUT_URL = "https://simfonie.kontomanager.at/index.php?dologout=2"
    _KONTOMANAGER_URL = "https://simfonie.kontomanager.at/kundendaten.php"
    _WEBSMS_URL = "https://simfonie.kontomanager.at/websms_send.php"

but I assume every A1 brand for which the *.kontomanager.at website exists works.

This would be:

> billitel.kontomanager.at
> educom.kontomanager.at
> fenercell.kontomanager.at
> goood.kontomanager.at
> kronemobile.kontomanager.at
> kundencenter.georg.at
> kuriermobil.kontomanager.at
> simfonie.kontomanager.at
> teleplanet.kontomanager.at
> wowww.kontomanager.at
> yooopi.kontomanager.at

**Comment by flowolf** [comment]
that's a great idea!
I'll add something that lets you configure the TLD. That seems to be all that is needed to switch.

**Comment by flowolf** [comment]
I released a beta (0.4.0b5) which is on pypi available for testing.

Please let me know if it works. And if you are using any other provider than Yesss, Simfonie or EDUCOM, what the parameters are, so I can add them to the possible providers.

 **Testing process**
```bash
pip3 install yessssms==0.4.0b5
yessssms --print-config-file > ~/.config/yessssms.conf
# edit the file, set MVNO or advanced settings:
vi ~/.config/yessssms.conf
yessssms --test


# OR
pip3 install yessssms==0.4.0b5
yessssms --test --mvno EDUCOM -l <YOUR_NUMBER> -p <YOUR_PASSWORD>
```

**Comment by J0s3f** [comment]
I can confirm that 

`yessssms --test --mvno EDUCOM`

and 

` yessssms --test --mvno SIMfonie`

work.

Thank you!

**Comment by flowolf** [comment]
perfect! expect a release shortly.
